### PR TITLE
Add meson build system

### LINKED ISSUE #19: coredump on connection destroy
latest MR introduced regression with GHashTable being destroyed with g_object_unref instead of g_hash_table_unref

trivial fix - just a reminder

### PR DESCRIPTION
**Pull request by rufferson**
See telepathyim/wocky#19

Same reasoning basically

Can fully build, check syntax and run tests. Also can run with empathy.
Twisted tests are ported to Python3. Some jingle tests are disabled (they use old google-session spec which I cannot find anywhere now).
Ubuntu 18.04 has too old meson and 20.04 has a bug in twisted python 3.8 - therefore a docker image is used for CI pipeline.
The dockers are from fdo/tp gitlab repo pre-built with Gabble dependencies.
Twisted tests revealed several bugs in gabble and wocky hence so far CI is using latest dev tip for wocky (~rufferson/wocky:gir) and essential fixes  are included into this MR to make tests succeed.

Closes #19

### CODE REVIEW

**Comment by rufferson** [comment]
uff, all twisted tests are in python2, don't think I'll have enough passion to port them to python3

**Comment by rufferson** [comment]
But otherwise looks fully working now (as far as I can test)
```
$ ninja -C _d test
ninja: Entering directory `_d'
[0/1] Running all tests.
 1/35 wocky / wocky-bare-contact-test            OK             0.01s
 2/35 wocky / wocky-caps-hash-test               OK             0.01s
 3/35 wocky / wocky-connector-test               OK             5.73s
 4/35 wocky / wocky-connector-test-tls1.2        OK             5.73s
 5/35 wocky / wocky-contact-factory-test         OK             0.03s
 6/35 wocky / wocky-data-form-test               OK             0.02s
 7/35 wocky / wocky-jid-validation-test          OK             0.03s
 8/35 wocky / wocky-loopback-test                OK             0.03s
 9/35 wocky / wocky-node-tree-test               OK             0.03s
10/35 wocky / wocky-pep-service-test             OK             0.02s
11/35 wocky / wocky-ping-test                    OK             4.91s
12/35 wocky / wocky-porter-test                  OK             0.08s
13/35 wocky / wocky-pubsub-node-test             OK             0.04s
14/35 wocky / wocky-pubsub-service-test          OK             0.04s
15/35 wocky / wocky-resource-contact-test        OK             0.02s
16/35 wocky / wocky-roster-test                  OK             0.04s
17/35 wocky / wocky-sasl-utils-test              OK             0.01s
18/35 wocky / wocky-scram-sha1-test              OK             0.04s
19/35 wocky / wocky-test-sasl-auth               OK             0.52s
20/35 wocky / wocky-session-test                 OK             0.02s
21/35 wocky / wocky-stanza-test                  OK             0.02s
22/35 wocky / wocky-tls-test                     OK             0.12s
23/35 wocky / wocky-sm-test                      OK             0.37s
24/35 wocky / wocky-utils-test                   OK             0.04s
25/35 wocky / wocky-xmpp-connection-test         OK             0.04s
26/35 wocky / wocky-xmpp-node-test               OK             0.02s
27/35 wocky / wocky-xmpp-reader-test             OK             0.02s
28/35 wocky / wocky-xmpp-readwrite-test          OK             0.02s
29/35 Telepathy_Gabble / test-dtube-unique-names OK             0.04s
30/35 Telepathy_Gabble / test-gabble-idle-weak   OK             0.03s
31/35 Telepathy_Gabble / test-handles            OK             0.03s
32/35 Telepathy_Gabble / test-jid-decode         OK             0.02s
33/35 Telepathy_Gabble / test-parse-message      OK             0.04s
34/35 Telepathy_Gabble / test-presence           OK             0.04s
35/35 Telepathy_Gabble / tp-error-from-wocky     OK             0.01s


Ok:                 35  
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/ruff/co/telepathy-gabble/_d/meson-logs/testlog.txt
$ GABBLE_PERSIST=1 GABBLE_DEBUG=all WOCKY_DEBUG=all G_MESSAGES_DEBUG=all /opt/data/lib2/libexec/telepathy-gabble 
(process:23300): tp-glib/proxy-DEBUG: 00:07:32.421: tp_proxy_dispose: 0x55bd0de761c0
(process:23300): tp-glib/proxy-DEBUG: 00:07:32.423: tp_proxy_invalidate: 0x55bd0de761c0: Proxy unreferenced
(process:23300): tp-glib/proxy-DEBUG: 00:07:32.423: tp_proxy_finalize: 0x55bd0de761c0
(process:23300): gabble-DEBUG: 00:07:32.423: gabble_plugin_loader_probe (../src/plugin-loader.c:141): probing /opt/data/lib2/lib/telepathy/gabble-0/plugins
** (process:23300): DEBUG: 00:07:32.423: gabble_plugin_create: loaded
(process:23300): gabble-DEBUG: 00:07:32.423: plugin_loader_try_to_load (../src/plugin-loader.c:104): loaded 'Gateway registration plugin' version 0.19.0 (/opt/data/lib2/lib/telepathy/gabble-0/plugins/libgateways.so), implementing these sidecars: org.freedesktop.Telepathy.Gabble.Plugin.Gateways
** (process:23300): DEBUG: 00:07:32.423: gabble_plugin_create: loaded
(process:23300): gabble-DEBUG: 00:07:32.423: plugin_loader_try_to_load (../src/plugin-loader.c:104): loaded 'XMPP console' version 0.19.0 (/opt/data/lib2/lib/telepathy/gabble-0/plugins/libconsole.so), implementing these sidecars: org.freedesktop.Telepathy.Gabble.Plugin.Console
(telepathy-gabble:23300): tp-glib-DEBUG: 00:07:32.424: started version 0.19.0 (telepathy-glib version 0.24.2)
(telepathy-gabble:23300): gabble-DEBUG: 00:09:08.085: gabble_connection_class_init (../src/connection.c:1026): Initializing (GabbleConnectionClass *)0x55bd0debe340
...
(telepathy-gabble:23300): wocky-DEBUG: 00:10:09.460: Parsing chunk: <a h='29' xmlns='urn:xmpp:sm:3'/>
(telepathy-gabble:23300): wocky-DEBUG: 00:10:09.460: _end_element_ns: Received stanza
* a xmlns='urn:xmpp:sm:3' h='29'
(telepathy-gabble:23300): wocky-DEBUG: 00:10:09.460: wocky_porter_sm_handle_h: ../subprojects/wocky/wocky/wocky-c2s-porter.c:1636: Acking 29 stanzas handled by the server
(telepathy-gabble:23300): wocky-DEBUG: 00:10:09.460: wocky_porter_sm_handle_h: ../subprojects/wocky/wocky/wocky-c2s-porter.c:1647: After ack 0(0) stanzas left in the queue
```

**Comment by rufferson** [comment]
And finally I did it. All tests except several jingles are working and revealed several bugs. Jingles - are using google-session and I cannot even find this specification to understand how it was supposed to work. So I temporarily disabled them till porting to jingle-session.

**Comment by rufferson** [comment]
technically this could be merged now although perhaps worth fixing wocky master and removing wocky.wrap kludge before that.

**Comment by pvuorela** [comment]
Hey now that you've mentioned python3 and the tests here, we on Sailfish have done some porting and would be surely nice to keep the delta smaller. Just that there are still lot of failing tests, over half of them passing though. Seems mostly strings vs bytes api changes, and might be often easy to handle but there are just so many of them. Don't know how much we have currently capacity to polish.

Patches there: https://git.sailfishos.org/mer-core/telepathy-gabble/tree/master/rpm

Any interest on those?

**Comment by rufferson** [comment]
Hi @pvuorela , I wish you came earlier to this :) I've already ported all tests to Py3 over past month and all of them (except jingle-share) succeed. I've currently marked jingle-share to SKIP as I don't quite understand how it was supposed to work. I'm now making final (new) unit tests for newly introduced functionality to make sure all is covered and green and will merge it.
That means the delta potentially might be significant even though I've also tried to keep low profile and mostly stick to b''/encode/decode stuff. You can see my delta [here](https://github.com/TelepathyIM/telepathy-gabble/pull/18/commits/180d64e7c95bd869807ae9d9a50865f8455741d0)

**Comment by pvuorela** [comment]
Yea, unfortunate if there was duplicate work, but if you have more tests passing perhaps we'll later just bump our checkout and get rid of our patch :)

**Pull request merged**
